services:
  frontend:
    container_name: bcgov-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app"
    ports:
      - 3008:3008
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: bcgov-backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/app"
    ports:
      - 3000:3000
