services:
  frontend:
    build:
      context: ./frontend
      dockerfile: /Dockerfile
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000 # Ask them what port the frontend should be at
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: /Dockerfile
    ports:
      - 3008:3008 # Ask them what port the backend should be at

